#!/bin/bash

if [ -z "$1" ] || [ "$1" == "1" ]; then

# Ecrivez le man à la suite du echo
    echo "
PROTOTYPE   :
    front()

UTILISATION :
    front

DESCRIPTION :
    Fais un cd vers le front de PopleeTalent

VALEUR DE RETOUR :
    Valeur de retour de cd
    0 si tout se passe bien

    [1/1]
"
fi
