#!/bin/bash

if [ "$1" == "-h" ]; then
    echo "\
UTILISATION :
    script [n° page]

ALIAS :
    scripts
    sc
    sl
    scriptlist
    man
    
DESCRIPTION :
    Affiche la liste des scripts perso"
    return 0
fi
if [ "$1" != "2" ]; then
    echo "\
SCRIPTS:

    Si vous avez besoins de plus d'infos faites man [le nom du script]
    ou [le nom du script] suivis de \"-h\"
    exemple : gdl -h

    addcompush  : Add / commit et push tous les fichiers modifiés
    br          : Donne le nom de la branche actuel
    d           : donne l'heure et s'actualise, press q to quit
    findarg     : On donne le nom d'un fichier, la fonction va chercher ce fichier,
    fm          : Affiche les fichiers modifié sur la branche active
    gdl         : Affiche les fichiers modifs du dernier commit
    man         : Affichage le manuel du script / fonction mis en argument
    reloadb     : Source auto du bashrc pour appliquer les changements dès la sauvegarde du fichier
                  et faire un cd dans le directory du cd si il n'y en a qu'un, 
                  sinon ça liste les possibilités
    rl          : git pull de rc et master puis reviens sur la branche active
    script      : Donne la liste de tous mes scripts

[1/2] Tapez \"script 2\", pour voir les alias -->
"
fi
if [ "$1" == "2" ]; then
    echo "\
ALIAS :
    ba          : build popleetalent sur la branche actuelle
    back        : ouvre le back, possibilité d'écrire \"cback\" pour ouvrir le back sur vsc
    c           : clear
    cb          : lance un reloadb avec l'ouverture du bashrc
    front       : ouvre le front, possibilité d'écrire \"cfront\" pour ouvrir le front sur vsc
    gc [nom branche]    : va sur rc / pull / créer une branche avec le nom donné
    gd [commit sha]     : montre les fichiers modifiés du commit choisit
    gp          : git pull
    gs          : git status
    lu          : ouvre Lucca, possibilité d'écrire \"clu\" pour ouvrir Lucca sur vsc
    master      : va sur master et pull
    ns          : lance un ng serve depuis n'importe ou
    ra          : rebuild popleetalent sur le dernier rc
    rc          : va sur rc et pull

[2/2] Tapez \"script\", pour voir les scripts <--
"
fi
